### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [mishabutorin/Find-Java-#1]
1. https://github.com/mishabutorin/Find-Java-/blob/42f429f405d2932f6f8e1c60c1447757ac3590bd/src/main/java/Main.java#L19-L21 Чтобы выкинуть из рассмотрения аргумент -d, лучше сделать `i++` при обработке `-d`.
1. Вместо нескольких `if` лучше использовать `switch`.
1. При ошибке программа должна завершаться с ненулевым кодом.
1. Повторюсь, было бы лучше, если функция поиска возвращала список найденных файлов, а печать на консоль производилась уже из `main`.
1. Не стоит использовать статические поля для передачи значений между функциями.
1. https://github.com/mishabutorin/Find-Java-/blob/42f429f405d2932f6f8e1c60c1447757ac3590bd/src/main/java/Main.java#L46 Зачем эта проверка? Директория тоже может быть искомым файлом. Это же касается и рекурсивного варианта.
1. Выводить найденный файл с путём следует так, чтобы заданная в `-d` директория поиска была префиксом. То есть абсолютный путь не подходит, нужно использовать относительный.
1. Не следует использовать абсолютные пути в тестах, иначе работать они будут только на одном компьютере.

**Comment by mishabutorin** [comment]
Исправил большинство замечаний, но, к сожалению все исправить не удалось.
https://github.com/mishabutorin/Find-Java-.git
 
--
Миша Буторин

**Comment by maximpetrov** [comment]
К сожалению, Вы исправили меньше половины замечаний. Исправлены 3, 6 и 8, остальные ещё актуальны.

**Comment by mishabutorin** [comment]
Исправлены пункты : 2, 5, 7
 
--
Миша Буторин

**Comment by maximpetrov** [comment]
1. Замечание 1 ещё актуально. Сейчас из-за этого у Вас нельзя найти файл в папке с таким же именем (то есть `-d test test` у Вас вызовет ошибку вместо того, чтобы искать файл test в папке test).
1. У Вас больше нет статического метода main, поэтому запустить Вашу утилиту невозможно.
1. По замечанию 7 Вы ничего не исправили.

**Comment by mishabutorin** [comment]
Исправил 1 замечание. 
Не понимаю как убрать статический метод.
 
 
--
Миша Буторин

**Comment by mishabutorin** [comment]
https://github.com/mishabutorin/trynumberfive  —ссылка на репозиторий с игрой.
Я писал Вам, что хочу сделать 3 вариации: обычную змейку, обратную змейку и змейку с уровнями.
У меня получилось сделать обычную змейку, к ней я сделал дополнение (золотое яблоко). Оно появляется при определённом количестве баллов и добавляет больше очков, чем обычное яблоко.
В меню у меня есть 2 пустых поля (settings, high score), в settings хочу реализовать изменение сложности, то есть при изменении сложности будет увеличиваться скорость змейки. В high score хочу реализовать добавление лучшего результата.
Обратную змейку до конца сделать не получилось. Я поменял счётчик очков (он изменяется также как идёт время игры), добавил заполнение поля едой. Не получилось сделать уменьшение змейки.
Не смог реализовать уровни, я хотел, чтобы каждый новый уровень был новым лабиринтом, но я не знаю как отрисовывать границы лабиринта. также хотел спросить, нужна ли вообще змейка с уровнями? 
И достаточно ли того, что есть сейчас и того, что планируется сделать. Спасибо.
 
--
Миша Буторин (3530901/90001)

**Comment by maximpetrov** [comment]
1. Первое замечание всё ещё актуально. Во-первых, Вы больше не сохраняете аргумент `-d`, а просто пропускаете его. Во-вторых, если бы Вы не забыли его сохранить, то всё ещё проигнорировали бы совпадающий с ним аргумент. Добавленный Вами тест не проверяет этот случай: файл должен называться именно testfolder, а не testfolder.txt.
1. Кстати, о тестах. Я попробовал запустить их, но они завершились с ошибкой. Не забывайте проверять, что Ваша программа работает, прежде чем отправлять на проверку.
1. Я не просил Вас убирать статические методы, в этой задаче не обязательно использовать объектно-ориентированный стиль, так что два статических метода меня устроят. Повторюсь, мне не нравится, что Вы передаёте значения между функциями (а точнее рекурсивными вызовами одно и той же функции) через статическое поле (то есть через глобальную переменную). Вместо него Вы вполне можете использовать возвращаемое значение функции. Кроме того, в задании ничего не сказано про требуемое поведение при отсутствии искомых файлов, но я бы предпочёл, чтобы программа просто ничего не выводила и не выходила с ошибкой (это поведение настоящей утилиты find). В этом случае Вам ничего передавать и не придётся.
1. Было бы неплохо, если бы Вы исправили пункт 7 исходных замечаний. Если Вы его не поняли, то поясняю: печатать результаты нужно относительно директории поиска, то есть, если задано `-d testfolder`, то результат должен быть `testfolder/testfolder2/new.txt`, если `-d testfolder/testfolder2` - `testfolder2/new.txt`, а если `-d /Users/valentinka/IdeaProjects/Find-Java-/testfolder` - `/Users/valentinka/IdeaProjects/Find-Java-/testfolder/testfolder2/new.txt`
